# Site settings
title: "Cabirol Florian"
baseurl: ""
url: "http://cabirol-florian.com" # the base hostname & protocol for your site
twitter_link: //www.twitter.com/wedevelopp
github_link:  //www.github.com/thatcheck
linkedin_link : //www.linkedin.com/in/cabirolflorian
permalink : pretty
# Build settings
markdown: kramdown
paginate : 10
exclude: ['README.md', 'CNAME', 'deploy.sh', 'src/', 'node_modules', 'package.json', 'gulpfile.js', '*.command',"bower_components", "bower.json"]
